In [1]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("../FH_lenti_editing_summary.csv")
df.head()

In [3]:
df_long = pd.melt(df, id_vars=['Spacer', 'target', 'strand', 'Spacer_length', 'spacer_add_g', 'scaffold'],
                  var_name='editing_position', value_name='eff')

df_long = df_long[df_long['eff'] != 0]

KeyError: "The following 'id_vars' are not present in the DataFrame: ['scaffold', 'spacer_add_g']"

In [18]:
df_long['editing_position'] = df_long['editing_position'].astype(int)

df_long = df_long[df_long['editing_position'] >= -25]

In [19]:
df_long

,Spacer,target,strand,Spacer_length,editing_position,eff
10926,AAAAATATCTTACCTGCAGTA,GAGGAAAATGAAAAATATCTTACCTGCAGTAATCTCCTTGC,0.0,21,-25,0.000575
10937,AAAAGTAAGCTTGACATTACCTC,TAGAAAATAAAAGTAAGCTTGACATTACCTCCTGTCCTGAT,0.0,23,-25,0.004985
10938,AAAAGTAAGCTTGACATTACCTC,TAGAAAATAAAAGTAAGCTTGACATTACCTCCTGTCCTGAT,1.0,23,-25,0.001656
10956,AAAGCCAAAGCTGACCTTATATCCT,CAAGTTAAAGCCAAAGCTGACCTTATATCCTTTTGCCACCA,1.0,25,-25,0.001918
10961,AAAGGTCACCTTGGCAGGAA,GGGTACAGGTCAAAGGTCACCTTGGCAGGAAGGCTCCGTCC,0.0,20,-25,0.000442
...,...,...,...,...,...,...
65435,TTGCTCCTCACCAGGAAATGA,GTTCTTTCATTTGCTCCTCACCAGGAAATGAGTGCCCAGAG,1.0,21,-1,0.001969
65487,TTTCACAGGCGCAGCAGAACA,CCTTTCTTTATTTCACAGGCGCAGCAGAACAAGTCCCTGAT,1.0,21,-1,0.000141
65516,TTTGCTCCTCACCAGGAAATGA,GTTCTTTCATTTGCTCCTCACCAGGAAATGAGTGCCCAGAG,0.0,22,-1,0.011210
65517,TTTGCTCCTCACCAGGAAATGA,GTTCTTTCATTTGCTCCTCACCAGGAAATGAGTGCCCAGAG,1.0,22,-1,0.001729
65518,TTTGTGATAAATGCTACAGA,ACACTTACTTTTTTGTGATAAATGCTACAGAGTCCCCTCTC,0.0,20,-1,0.000931

In [20]:

def extract_sequence(dna, position):
    index_from_end = position + 10
    start_index = len(dna) - index_from_end - 3 
    end_index = len(dna) - index_from_end + 3  

    result = ['N'] * 7

    for i in range(max(0, start_index), min(len(dna), end_index + 1)):
        result[i - start_index] = dna[i]

    return ''.join(result)

In [21]:
df_long['context'] = df_long.apply(lambda row: extract_sequence(row['target'], row['editing_position']*-1), axis=1)

In [22]:
df_long

,Spacer,target,strand,Spacer_length,editing_position,eff,context
10926,AAAAATATCTTACCTGCAGTA,GAGGAAAATGAAAAATATCTTACCTGCAGTAATCTCCTTGC,0.0,21,-25,0.000575,GAAAATG
10937,AAAAGTAAGCTTGACATTACCTC,TAGAAAATAAAAGTAAGCTTGACATTACCTCCTGTCCTGAT,0.0,23,-25,0.004985,AAAATAA
10938,AAAAGTAAGCTTGACATTACCTC,TAGAAAATAAAAGTAAGCTTGACATTACCTCCTGTCCTGAT,1.0,23,-25,0.001656,AAAATAA
10956,AAAGCCAAAGCTGACCTTATATCCT,CAAGTTAAAGCCAAAGCTGACCTTATATCCTTTTGCCACCA,1.0,25,-25,0.001918,GTTAAAG
10961,AAAGGTCACCTTGGCAGGAA,GGGTACAGGTCAAAGGTCACCTTGGCAGGAAGGCTCCGTCC,0.0,20,-25,0.000442,TACAGGT
...,...,...,...,...,...,...,...
65435,TTGCTCCTCACCAGGAAATGA,GTTCTTTCATTTGCTCCTCACCAGGAAATGAGTGCCCAGAG,1.0,21,-1,0.001969,ATGAGTG
65487,TTTCACAGGCGCAGCAGAACA,CCTTTCTTTATTTCACAGGCGCAGCAGAACAAGTCCCTGAT,1.0,21,-1,0.000141,AACAAGT
65516,TTTGCTCCTCACCAGGAAATGA,GTTCTTTCATTTGCTCCTCACCAGGAAATGAGTGCCCAGAG,0.0,22,-1,0.011210,ATGAGTG
65517,TTTGCTCCTCACCAGGAAATGA,GTTCTTTCATTTGCTCCTCACCAGGAAATGAGTGCCCAGAG,1.0,22,-1,0.001729,ATGAGTG
65518,TTTGTGATAAATGCTACAGA,ACACTTACTTTTTTGTGATAAATGCTACAGAGTCCCCTCTC,0.0,20,-1,0.000931,CAGAGTC

In [24]:
df_long.rename(columns={'Spacer': 'spacer'}, inplace=True)
df_long.rename(columns={'Spacer_length': 'spacer_length'}, inplace=True)
df_long.rename(columns={'editing_position': 'pos'}, inplace=True)

In [25]:
df_long.head()

,spacer,target,strand,spacer_length,pos,eff,context
10926,AAAAATATCTTACCTGCAGTA,GAGGAAAATGAAAAATATCTTACCTGCAGTAATCTCCTTGC,0.0,21,-25,0.000575,GAAAATG
10937,AAAAGTAAGCTTGACATTACCTC,TAGAAAATAAAAGTAAGCTTGACATTACCTCCTGTCCTGAT,0.0,23,-25,0.004985,AAAATAA
10938,AAAAGTAAGCTTGACATTACCTC,TAGAAAATAAAAGTAAGCTTGACATTACCTCCTGTCCTGAT,1.0,23,-25,0.001656,AAAATAA
10956,AAAGCCAAAGCTGACCTTATATCCT,CAAGTTAAAGCCAAAGCTGACCTTATATCCTTTTGCCACCA,1.0,25,-25,0.001918,GTTAAAG
10961,AAAGGTCACCTTGGCAGGAA,GGGTACAGGTCAAAGGTCACCTTGGCAGGAAGGCTCCGTCC,0.0,20,-25,0.000442,TACAGGT

In [26]:
df_long.to_csv('../FH_lenti_editing_summary_processed.csv', index=False)

In [1]:
import numpy as np 
import pandas as pd 
import itertools


def update_dataframe(df, feature_list):
    """
    Takes in a processed dataframe and a list of features. Will create columns from specified paired features and then remove the original columns from the dataframe. Ignores the last feature if an odd number of features are provided.
    
    Parameters:
    df (pandas.DataFrame): The dataframe to be updated.
    feature_list (list): List of column names in the dataframe to be used for creating paired features.
    
    Returns:
    pandas.DataFrame: The updated dataframe with new paired features and without the original features used for pairing.
    """
    bin_dict = {(0, 0): 0, (0, 1): 1, (1, 0): 2, (1, 1): 3}

    unwanted_list = ['SGN_Strand', 'Editing_Position', 'Acontent', 'Tcontent', 'Ccontent', 'Gcontent', 'GCcontent', 'Editing_mt']
    begin = 'SGN_mt_w_'
    
    feature_list = [feature for feature in feature_list if feature not in unwanted_list and not feature.startswith(begin)]
    
    for i in range(0, len(feature_list) - len(feature_list) % 2, 2):
        feature1 = feature_list[i]
        feature2 = feature_list[i + 1]
        
        new_column_name = f"paired_{feature1}_{feature2}"
        
        df[new_column_name] = df[[feature1, feature2]].apply(lambda row: bin_dict[(row[feature1], row[feature2])], axis=1)
        
        df.drop(columns=[feature1, feature2], inplace=True)

    return df

In [ ]:
df = update_dataframe

In [1]:
amp = ['Editing_Position', 'SGN_P-9_C', 'Context_P1_C', 'Editing_P-14', 'SGN_P-28_C', 'SGN_P1_A', 'SGN_P-11_G', 'Editing_P-15', 'Context_P2_C', 'Acontent', 'SGN_P-19_C', 'Editing_P-9', 'SGN_P-10_A', 'SGN_P-8_T', 'SGN_P-11_A', 'Editing_P-18', 'SGN_P1_G', 'SGN_P-16_C', 'Context_P1_G', 'SGN_P-3_A', 'SGN_P2_T', 'GCcontent', 'SGN_P-22_T', 'SGN_P-15_C', 'SGN_P-9_G', 'SGN_P-15_T', 'SGN_P-12_C', 'SGN_P6_C', 'Context_P3_T', 'SGN_P-26_A', 'SGN_P9_A', 'Context_P-3_C', 'Ccontent', 'SGN_P-23_C', 'SGN_P-8_C', 'SGN_P-14_A', 'Context_P-2_T', 'SGN_P6_G', 'Context_P3_C', 'Tcontent', 'SGN_P-5_A', 'Context_P-1_G', 'Context_P-3_T', 'SGN_mt_w_24', 'SGN_P-3_C', 'Context_P-1_T', 'SGN_P-24_T', 'SGN_P-19_T', 'SGN_P-2_G', 'Gcontent', 'SGN_P-16_A', 'Editing_P-17']

In [2]:
cv = ['Editing_Position', 'SGN_P2_T', 'SGN_P6_A', 'GCcontent', 'SGN_P8_T', 'SGN_P-9_A', 'Gcontent', 'SGN_P-11_A', 'SGN_P2_G', 'SGN_P1_G', 'Acontent', 'SGN_P-6_A', 'SGN_P6_G', 'Tcontent', 'SGN_P-26_G', 'SGN_P-1_A', 'SGN_P-3_A', 'SGN_P-2_A', 'SGN_P-12_G', 'SGN_P-24_G', 'SGN_P-21_C', 'SGN_P-20_A', 'SGN_P-14_A', 'Context_P1_C', 'SGN_P-19_T','SGN_P-9_T', 'SGN_P-22_C', 'SGN_P-15_A', 'SGN_P-8_G', 'SGN_P-1_T', 'Context_P-1_T', 'SGN_P-5_A', 'SGN_P3_T', 'Ccontent', 'SGN_P-9_C', 'SGN_P-23_T', 'SGN_P-13_T', 'SGN_P1_A', 'Editing_P-10', 'SGN_P0_C', 'SGN_P7_C', 'Context_P3_G', 'Context_P-1_C', 'Context_P2_G', 'Context_P-3_G', 'SGN_P-29_G', 'SGN_mt_w_8']

In [3]:
fh = ['Editing_Position', 'SGN_P2_T', 'Gcontent', 'SGN_P-10_T', 'SGN_P-7_G', 'Context_P-1_T', 'Acontent', 'Tcontent', 'SGN_P1_G', 'SGN_P-25_G', 'SGN_P-22_G', 'Context_P-3_G', 'SGN_P-7_T', 'SGN_P-23_C', 'Ccontent', 'SGN_P-6_C', 'SGN_P-21_C', 'SGN_P-3_A', 'GCcontent', 'SGN_P9_C', 'Context_P1_C', 'SGN_P3_C', 'SGN_P8_G', 'SGN_P-7_C', 'SGN_mt_w_28', 'Editing_mt', 'Context_P3_C', 'Context_P-2_G', 'Context_P-1_C']

In [5]:
fh_set = set(fh)
cv_set = set(cv)
amp_set= set(amp)

similar_features = fh_set.intersection(cv_set, amp_set)

In [6]:
similar_features

{'Acontent',
 'Ccontent',
 'Context_P-1_T',
 'Context_P1_C',
 'Editing_Position',
 'GCcontent',
 'Gcontent',
 'SGN_P-3_A',
 'SGN_P1_G',
 'SGN_P2_T',
 'Tcontent'}